export const ADD_FLOW = 'ADD_FLOW';
export const ADD_FLOW_SUCCESS = 'ADD_FLOW_SUCCESS';
export const ADD_FLOW_ERROR = 'ADD_FLOW_ERROR';

export const FETCH_FLOW = 'FETCH_FLOW';
export const FETCH_FLOW_SUCCESS = 'FETCH_FLOW_SUCCESS';
export const FETCH_FLOW_ERROR = 'FETCH_FLOW_ERROR';

export const UPDATE_FLOW = 'UPDATE_FLOW';
export const UPDATE_FLOW_SUCCESS = 'UPDATE_FLOW_SUCCESS';
export const UPDATE_FLOW_ERROR = 'UPDATE_FLOW_ERROR';


export const DELETE_FLOW = 'DELETE_FLOW';
export const DELETE_FLOW_SUCCESS = 'DELETE_FLOW_SUCCESS';
export const DELETE_FLOW_ERROR = 'DELETE_FLOW_ERROR';

export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const UPDATE_USER = 'UPDATE_USER'

export const FETCH_SETTINGS = 'FETCH_SETTINGS'
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS'
export const FETCH_SETTINGS_ERROR = 'FETCH_SETTINGS_ERROR'

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS'
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS'
export const UPDATE_SETTINGS_ERROR = 'UPDATE_SETTINGS_ERROR'

export const ADD_LOG = 'ADD_LOG';
export const ADD_LOG_SUCCESS = 'ADD_LOG_SUCCESS';
export const ADD_LOG_ERROR = 'ADD_LOG_ERROR';

export const FETCH_LOGS = 'FETCH_LOGS';
export const FETCH_LOGS_SUCCESS = 'FETCH_LOGS_SUCCESS';
export const FETCH_LOGS_ERROR = 'FETCH_LOGS_ERROR';

export const UPDATE_LOG = 'UPDATE_LOG';
export const UPDATE_LOG_SUCCESS = 'UPDATE_LOG_SUCCESS';
export const UPDATE_LOG_ERROR = 'UPDATE_LOG_ERROR';


export const DELETE_LOG = 'DELETE_LOG';
export const DELETE_LOG_SUCCESS = 'DELETE_LOG_SUCCESS';
export const DELETE_LOG_ERROR = 'DELETE_LOG_ERROR';