# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  docker-publish:
    docker:
      - image: circleci/python:3.6
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .
      - setup_remote_docker
      - run:
          name: Check Environment Variables
          command: |
            if [[ -z "${DOCKER_LOGIN}" ]]; then
            echo "DOCKER_LOGIN is not set, will not be able to push image."
            exit 1
            fi
            if [[ -z "${DOCKER_PASSWORD}" ]]; then
            echo "DOCKER_PASSWORD is not set, will not be able to push image."
            exit 1
            fi
      - run:
          name: Docker Login
          command: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}" docker.io
      - run:
          name: Build Docker Image
          command: |
            docker build \
               \
              -f Dockerfile -t \
              docker.io/$DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 \
              .
      - run:
          name: Push Docker Image
          command: |
            if [[ $CIRCLE_NODE_INDEX == 0 ]]; then
            docker push docker.io/$DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
            fi
            if [[ -z "${DOCKER_PASSWORD}" ]]; then
            echo "DOCKER_PASSWORD is not set, will not be able to push image."
            exit 1
            fi
      - run:
          name: Docker Login
          command: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}" docker.io
      - run:
          name: Build Docker Image
          command: |
            docker build \
               \
              -f Dockerfile -t \
              docker.io/$DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 \
              .
      - run:
          name: Push Docker Image
          command: |
            if [[ $CIRCLE_NODE_INDEX == 0 ]]; then
              docker push docker.io/$DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
            fi
workflows:
  build-test-deploy:
    jobs:
      - docker-publish:
          filters:
            branches:
              only: master
