version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.6
workflows:
  build_and_publish_docker_image:
    jobs:
      - docker-publish/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: latest
          filters:
            branches:
              only: master
